version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "${REDIS_DOCKER_PORT}:6379"
    networks:
      - net

  authpsx:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${AUTH_PSX_PASSWORD}
      POSTGRES_USER: ${AUTH_PSX_USER}
      POSTGRES_DB: ${AUTH_PSX_DBNAME}
    volumes:
      - ./scripts/sql/auth/init:/docker-entrypoint-initdb.d
    ports:
      - "${AUTH_PSX_DOCKER_PORT}:5432"
    networks:
      - net

  bannerpsx:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: ${BANNER_PSX_DBNAME}
      POSTGRES_PASSWORD: ${BANNER_PSX_PASSWORD}
      POSTGRES_USER: ${BANNER_PSX_USER}
    volumes:
      - ./scripts/sql/banner/init:/docker-entrypoint-initdb.d
    ports:
      - "${BANNER_PSX_DOCKER_PORT}:5432"
    networks:
      - net

  nginx:
    image: "nginx:latest"
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - authapp
      - bannerapp
    networks:
      - net

  bannerapp:
    build:
      context: .
      dockerfile: Dockerfile_banner
    ports:
      - "${BANNER_APP_PORT}:${BANNER_APP_PORT}"
    depends_on:
      - redis
      - authpsx
      - bannerpsx
    env_file:
      ./.env
    networks:
      - net

  authapp:
    build:
      context: .
      dockerfile: Dockerfile_auth
    ports:
      - "${AUTH_APP_PORT}:${AUTH_APP_PORT}"
      - "${AUTH_GRPC_PORT}:${AUTH_GRPC_PORT}"
    depends_on:
      - redis
      - authpsx
      - bannerpsx
    env_file:
      ./.env
    networks:
      - net

networks:
  net:
    driver: bridge